"""從 revenue_records 推算每位律師對應的部門，輸出 JS const 片段"""
import httpx, os, io, sys, json
from dotenv import load_dotenv
from collections import Counter
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))
u = os.environ["SUPABASE_URL"]
k = os.environ["SUPABASE_SERVICE_KEY"]
H = {"apikey": k, "Authorization": f"Bearer {k}"}


def fetch_all(path, params):
    rows = []
    offset = 0
    page = 1000
    while True:
        p = dict(params); p["limit"] = str(page); p["offset"] = str(offset)
        r = httpx.get(f"{u}/rest/v1/{path}", params=p, headers=H, timeout=60)
        r.raise_for_status()
        data = r.json()
        rows.extend(data)
        if len(data) < page: break
        offset += page
    return rows


OFFICE_TO_CITY = {
    "台北所": "台北",
    "桃園所": "桃園",
    "新竹所": "新竹",
    "台中所": "台中",
    "台南所": "台南",
    "高雄所": "高雄",
}

# 非諮詢律師：lawyers 表裡有但不做諮詢業務（財務、法務、客服、dummy 等），
# 不要進 LAWYER_DEPARTMENTS — 否則他們會被歸到部門 tab。
# 註：lawyers.role 不可靠（admin 同時包含創辦人雷皓明與財務張飛宇），
#     legal_staff 都是法務不是諮詢律師。要明確列 ID 排除。
NON_CONSULTING_LAWYER_IDS = {
    # admin 但非諮詢
    "76636726-2f80-4888-895f-ccbaf7c2ba81",  # 張飛宇 — 財務主管
    "27ea064c-98eb-477e-8c61-13b052ab23ed",  # 股東 — dummy
    # manager
    "ff69ecc5-224b-4ce8-8a6e-618721927479",  # 蘇思蓓
    "7794fbee-c262-4a66-acba-11b712833165",  # 客戶關係部 — 部門帳號
    # legal_staff（法務 — 不是諮詢律師）
    "9409dfa5-4a02-45c0-9981-6b561a13141e",  # 謝依璇
    "00068630-51ba-4239-890e-59bfb8e69cbd",  # 賴佳瑩
    "3822ab76-80f0-4234-afef-2814a834ca70",  # 曾靖雯
    "5b1d9857-df6f-4106-afd3-5482fa14b56a",  # 董沐穎
    "62a18b12-394a-44af-b9c8-1538626a84df",  # 江欣柔
    "27d25c54-6fa5-4b30-8367-851007e0a845",  # 黃逸庭
}

# 手動覆寫：auto-detect 從 lawyers.office + revenue_records 推算錯誤時用
# 例：lawyers.office 是「喆律法律事務所」這種沒城市資訊的，會 fallback 到
#     revenue_records 最常出現的 office，但實際身分可能不是。
LAWYER_DEPT_OVERRIDE = {
    "70623a0d-c3dd-47d5-abd7-9061fb39f8a8": "合署(司法官)",  # 方心瑜
}

# 1. 律師列表
lawyers = fetch_all("lawyers", {"select": "id,name,office,role,is_active"})
print(f"律師總數：{len(lawyers)}")

# 2. revenue_records 累計律師 → office 次數
rev = fetch_all("revenue_records", {"select": "responsible_lawyer,assigned_lawyers,office"})
print(f"revenue_records：{len(rev)}")

name_to_office = {}  # name -> Counter(office)
for r in rev:
    off = r.get("office")
    if not off: continue
    # responsible_lawyer 可能是單人或「A, B」
    for field in ["responsible_lawyer", "assigned_lawyers"]:
        v = (r.get(field) or "").strip()
        if not v: continue
        for nm in [x.strip() for x in v.replace("、", ",").split(",") if x.strip()]:
            name_to_office.setdefault(nm, Counter())[off] += 1

# 3. 為每位律師指派部門
result = {}
unresolved = []
for l in lawyers:
    lid = l["id"]; name = l["name"]; off = (l.get("office") or "").strip()
    if lid in NON_CONSULTING_LAWYER_IDS:
        continue
    if "(合署)" in off or off.endswith("(合署)"):
        # 不是司法官的合署 → 合署
        if "司法官" in off:
            result[lid] = "合署(司法官)"
        else:
            result[lid] = "合署"
    elif "司法官合署" in off:
        result[lid] = "合署(司法官)"
    else:
        # 從 revenue_records 最常出現的 office 推算
        counter = name_to_office.get(name)
        if counter:
            top_off = counter.most_common(1)[0][0]
            city = OFFICE_TO_CITY.get(top_off)
            if city:
                result[lid] = city
            else:
                result[lid] = None
                unresolved.append((name, top_off))
        else:
            result[lid] = None
            unresolved.append((name, "(revenue_records 無資料)"))

# 3.5 套用手動覆寫
for lid, dept in LAWYER_DEPT_OVERRIDE.items():
    if lid in result:
        result[lid] = dept

# 4. 統計
from collections import Counter as C
dept_count = C(result.values())
print()
print("部門分布:")
for dept, cnt in sorted(dept_count.items(), key=lambda x: -x[1] if x[0] else 0):
    print(f"  {dept}: {cnt}")

if unresolved:
    print()
    print(f"無法判定部門的律師 ({len(unresolved)})：")
    for nm, reason in unresolved[:20]:
        print(f"  {nm}: {reason}")

# 5. 輸出 JS const
js_lines = ["// Auto-generated by scripts/compute_lawyer_departments.py",
            "// Maps lawyer_id -> department",
            "var LAWYER_DEPARTMENTS = {"]
for l in sorted(lawyers, key=lambda x: x["name"]):
    if l["id"] in NON_CONSULTING_LAWYER_IDS:
        continue
    dept = result.get(l["id"])
    if dept is None: dept = ""  # 讓前端視為未分類
    js_lines.append(f'  "{l["id"]}": "{dept}",  // {l["name"]}')
js_lines.append("};")
js_lines.append("")
js_lines.append("var DEPARTMENT_ORDER = ['台北','桃園','新竹','台中','台南','高雄','合署','合署(司法官)'];")
js_lines.append("")
js_lines.append("// ──────────────────────────────────────────────────────────────────────────")
js_lines.append("// 律師部門異動歷史：在指定日期之前，律師歸屬到不同部門")
js_lines.append("// 用 getDeptForLawyer(lawyer_id, dateStr) 替代直接讀 LAWYER_DEPARTMENTS[id]，")
js_lines.append("// 才能讓「轉所之前」的歷史案件正確歸到原所別。")
js_lines.append("// 現職部門仍由 LAWYER_DEPARTMENTS 決定。")
js_lines.append("// ──────────────────────────────────────────────────────────────────────────")
js_lines.append("var LAWYER_DEPT_HISTORY = {")
js_lines.append("  // 李昭萱：2025-06 前是中所所長，之後轉合署")
js_lines.append('  "21e50125-59e7-4ac8-8729-470b7eea40f0": [')
js_lines.append("    { before: '2025-06-01', dept: '台中' },")
js_lines.append("  ],")
js_lines.append("};")
js_lines.append("")
js_lines.append("function getDeptForLawyer(lawyerId, dateOrMonth) {")
js_lines.append("  var hist = LAWYER_DEPT_HISTORY[lawyerId];")
js_lines.append("  if (hist && dateOrMonth) {")
js_lines.append("    // 支援 YYYY-MM 或 YYYY-MM-DD；前者補齊為月初")
js_lines.append("    var d = dateOrMonth.length === 7 ? dateOrMonth + '-01' : dateOrMonth;")
js_lines.append("    for (var i = 0; i < hist.length; i++) {")
js_lines.append("      if (d < hist[i].before) return hist[i].dept;")
js_lines.append("    }")
js_lines.append("  }")
js_lines.append("  return (typeof LAWYER_DEPARTMENTS !== 'undefined') ? LAWYER_DEPARTMENTS[lawyerId] : undefined;")
js_lines.append("}")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "lawyer_departments.js")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(js_lines))
print()
print(f"✓ JS 片段已寫入：{out_path}")
print(f"  共 {len(lawyers)} 位律師的 department 對應")
